// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/rbac/v1"
)

// IAccessControlRuleProvider is an autogenerated mock type for the IAccessControlRuleProvider type
type IAccessControlRuleProvider struct {
	mock.Mock
}

// ReadOnlyRoleRules provides a mock function with no fields
func (_m *IAccessControlRuleProvider) ReadOnlyRoleRules() []v1.PolicyRule {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadOnlyRoleRules")
	}

	var r0 []v1.PolicyRule
	if rf, ok := ret.Get(0).(func() []v1.PolicyRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.PolicyRule)
		}
	}

	return r0
}

// ReadWriteRoleRules provides a mock function with no fields
func (_m *IAccessControlRuleProvider) ReadWriteRoleRules() []v1.PolicyRule {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadWriteRoleRules")
	}

	var r0 []v1.PolicyRule
	if rf, ok := ret.Get(0).(func() []v1.PolicyRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.PolicyRule)
		}
	}

	return r0
}

// WorkerClusterRoleRules provides a mock function with no fields
func (_m *IAccessControlRuleProvider) WorkerClusterRoleRules() []v1.PolicyRule {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkerClusterRoleRules")
	}

	var r0 []v1.PolicyRule
	if rf, ok := ret.Get(0).(func() []v1.PolicyRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.PolicyRule)
		}
	}

	return r0
}

// NewIAccessControlRuleProvider creates a new instance of IAccessControlRuleProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccessControlRuleProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccessControlRuleProvider {
	mock := &IAccessControlRuleProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
