// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// INamespaceService is an autogenerated mock type for the INamespaceService type
type INamespaceService struct {
	mock.Mock
}

// DeleteNamespace provides a mock function with given fields: ctx, namespace
func (_m *INamespaceService) DeleteNamespace(ctx context.Context, namespace string) (reconcile.Result, error) {
	ret := _m.Called(ctx, namespace)

	var r0 reconcile.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) reconcile.Result); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReconcileProjectNamespace provides a mock function with given fields: ctx, namespace, owner
func (_m *INamespaceService) ReconcileProjectNamespace(ctx context.Context, namespace string, owner client.Object) (reconcile.Result, error) {
	ret := _m.Called(ctx, namespace, owner)

	var r0 reconcile.Result
	if rf, ok := ret.Get(0).(func(context.Context, string, client.Object) reconcile.Result); ok {
		r0 = rf(ctx, namespace, owner)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, client.Object) error); ok {
		r1 = rf(ctx, namespace, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
