// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1alpha1 "github.com/kubeslice/kubeslice-controller/apis/controller/v1alpha1"
)

// ISliceIpamService is an autogenerated mock type for the ISliceIpamService type
type ISliceIpamService struct {
	mock.Mock
}

// AllocateSubnetForCluster provides a mock function with given fields: ctx, sliceName, clusterName, namespace
func (_m *ISliceIpamService) AllocateSubnetForCluster(ctx context.Context, sliceName string, clusterName string, namespace string) (string, error) {
	ret := _m.Called(ctx, sliceName, clusterName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for AllocateSubnetForCluster")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, sliceName, clusterName, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, sliceName, clusterName, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sliceName, clusterName, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSliceIpam provides a mock function with given fields: ctx, sliceConfig
func (_m *ISliceIpamService) CreateSliceIpam(ctx context.Context, sliceConfig *v1alpha1.SliceConfig) error {
	ret := _m.Called(ctx, sliceConfig)

	if len(ret) == 0 {
		panic("no return value specified for CreateSliceIpam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.SliceConfig) error); ok {
		r0 = rf(ctx, sliceConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSliceIpam provides a mock function with given fields: ctx, sliceName, namespace
func (_m *ISliceIpamService) DeleteSliceIpam(ctx context.Context, sliceName string, namespace string) error {
	ret := _m.Called(ctx, sliceName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSliceIpam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sliceName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClusterSubnet provides a mock function with given fields: ctx, sliceName, clusterName, namespace
func (_m *ISliceIpamService) GetClusterSubnet(ctx context.Context, sliceName string, clusterName string, namespace string) (string, error) {
	ret := _m.Called(ctx, sliceName, clusterName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterSubnet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, sliceName, clusterName, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, sliceName, clusterName, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sliceName, clusterName, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReconcileSliceIpam provides a mock function with given fields: ctx, req
func (_m *ISliceIpamService) ReconcileSliceIpam(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileSliceIpam")
	}

	var r0 reconcile.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) (reconcile.Result, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) reconcile.Result); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, reconcile.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseSubnetForCluster provides a mock function with given fields: ctx, sliceName, clusterName, namespace
func (_m *ISliceIpamService) ReleaseSubnetForCluster(ctx context.Context, sliceName string, clusterName string, namespace string) error {
	ret := _m.Called(ctx, sliceName, clusterName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseSubnetForCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, sliceName, clusterName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISliceIpamService creates a new instance of ISliceIpamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISliceIpamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISliceIpamService {
	mock := &ISliceIpamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
