// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	controllerv1alpha1 "github.com/kubeslice/kubeslice-controller/apis/controller/v1alpha1"
	mock "github.com/stretchr/testify/mock"

	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1alpha1 "github.com/kubeslice/kubeslice-controller/apis/worker/v1alpha1"
)

// IWorkerSliceConfigService is an autogenerated mock type for the IWorkerSliceConfigService type
type IWorkerSliceConfigService struct {
	mock.Mock
}

// ComputeClusterMap provides a mock function with given fields: clusterNames, workerSliceConfigs
func (_m *IWorkerSliceConfigService) ComputeClusterMap(clusterNames []string, workerSliceConfigs []v1alpha1.WorkerSliceConfig) map[string]int {
	ret := _m.Called(clusterNames, workerSliceConfigs)

	if len(ret) == 0 {
		panic("no return value specified for ComputeClusterMap")
	}

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func([]string, []v1alpha1.WorkerSliceConfig) map[string]int); ok {
		r0 = rf(clusterNames, workerSliceConfigs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// CreateMinimalWorkerSliceConfig provides a mock function with given fields: ctx, clusters, namespace, label, name, sliceSubnet, clusterCidr, sliceGwSvcTypeMap, sliceConfig, sipam
func (_m *IWorkerSliceConfigService) CreateMinimalWorkerSliceConfig(ctx context.Context, clusters []string, namespace string, label map[string]string, name string, sliceSubnet string, clusterCidr string, sliceGwSvcTypeMap map[string]*controllerv1alpha1.SliceGatewayServiceType, sliceConfig *controllerv1alpha1.SliceConfig, sipam interface{}) (map[string]int, error) {
	ret := _m.Called(ctx, clusters, namespace, label, name, sliceSubnet, clusterCidr, sliceGwSvcTypeMap, sliceConfig, sipam)

	if len(ret) == 0 {
		panic("no return value specified for CreateMinimalWorkerSliceConfig")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, map[string]string, string, string, string, map[string]*controllerv1alpha1.SliceGatewayServiceType, *controllerv1alpha1.SliceConfig, interface{}) (map[string]int, error)); ok {
		return rf(ctx, clusters, namespace, label, name, sliceSubnet, clusterCidr, sliceGwSvcTypeMap, sliceConfig, sipam)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, map[string]string, string, string, string, map[string]*controllerv1alpha1.SliceGatewayServiceType, *controllerv1alpha1.SliceConfig, interface{}) map[string]int); ok {
		r0 = rf(ctx, clusters, namespace, label, name, sliceSubnet, clusterCidr, sliceGwSvcTypeMap, sliceConfig, sipam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string, map[string]string, string, string, string, map[string]*controllerv1alpha1.SliceGatewayServiceType, *controllerv1alpha1.SliceConfig, interface{}) error); ok {
		r1 = rf(ctx, clusters, namespace, label, name, sliceSubnet, clusterCidr, sliceGwSvcTypeMap, sliceConfig, sipam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMinimalWorkerSliceConfigForNoNetworkSlice provides a mock function with given fields: ctx, clusters, namespace, label, name
func (_m *IWorkerSliceConfigService) CreateMinimalWorkerSliceConfigForNoNetworkSlice(ctx context.Context, clusters []string, namespace string, label map[string]string, name string) error {
	ret := _m.Called(ctx, clusters, namespace, label, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateMinimalWorkerSliceConfigForNoNetworkSlice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, map[string]string, string) error); ok {
		r0 = rf(ctx, clusters, namespace, label, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWorkerSliceConfigByLabel provides a mock function with given fields: ctx, label, namespace
func (_m *IWorkerSliceConfigService) DeleteWorkerSliceConfigByLabel(ctx context.Context, label map[string]string, namespace string) error {
	ret := _m.Called(ctx, label, namespace)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkerSliceConfigByLabel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string) error); ok {
		r0 = rf(ctx, label, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListWorkerSliceConfigs provides a mock function with given fields: ctx, ownerLabel, namespace
func (_m *IWorkerSliceConfigService) ListWorkerSliceConfigs(ctx context.Context, ownerLabel map[string]string, namespace string) ([]v1alpha1.WorkerSliceConfig, error) {
	ret := _m.Called(ctx, ownerLabel, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkerSliceConfigs")
	}

	var r0 []v1alpha1.WorkerSliceConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string) ([]v1alpha1.WorkerSliceConfig, error)); ok {
		return rf(ctx, ownerLabel, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string) []v1alpha1.WorkerSliceConfig); ok {
		r0 = rf(ctx, ownerLabel, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.WorkerSliceConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, string) error); ok {
		r1 = rf(ctx, ownerLabel, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReconcileWorkerSliceConfig provides a mock function with given fields: ctx, req
func (_m *IWorkerSliceConfigService) ReconcileWorkerSliceConfig(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileWorkerSliceConfig")
	}

	var r0 reconcile.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) (reconcile.Result, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) reconcile.Result); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, reconcile.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIWorkerSliceConfigService creates a new instance of IWorkerSliceConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWorkerSliceConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWorkerSliceConfigService {
	mock := &IWorkerSliceConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
