# permissions for end users to view vpnkeyrotations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpnkeyrotation-viewer-role
rules:
- apiGroups:
  - controller.kubeslice.io.kubeslice.io
  resources:
  - vpnkeyrotations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.kubeslice.io.kubeslice.io
  resources:
  - vpnkeyrotations/status
  verbs:
  - get
