# permissions for end users to edit workerslicegwrecyclers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerslicegwrecycler-editor-role
rules:
- apiGroups:
  - worker.kubeslice.io
  resources:
  - workerslicegwrecyclers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - worker.kubeslice.io
  resources:
  - workerslicegwrecyclers/status
  verbs:
  - get
