# permissions for end users to view workerslicegwrecyclers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerslicegwrecycler-viewer-role
rules:
- apiGroups:
  - worker.kubeslice.io
  resources:
  - workerslicegwrecyclers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - worker.kubeslice.io
  resources:
  - workerslicegwrecyclers/status
  verbs:
  - get
