package events

// Autogenerated file. DO NOT MODIFY DIRECTLY!
/*
 *  Copyright (c) 2022 Avesha, Inc. All rights reserved.
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import "github.com/kubeslice/kubeslice-monitoring/pkg/events"

var eventsMap = map[events.EventName]*events.EventSchema{
	"LicenseSecretNotFound": {
		Name:                "LicenseSecretNotFound",
		Reason:              "LicenseNotFound",
		Action:              "LicenseValidation",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Secret with license config not found. Please ensure to create license secret if this is airgapped cluster.",
	},
	"MachineFileNotFound": {
		Name:                "MachineFileNotFound",
		Reason:              "MachineFileNotFound",
		Action:              "FetchMachineFileFromSecret",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Machine File not present in license secret. Please contact kubeslice support team.",
	},
	"MachineFileInvalid": {
		Name:                "MachineFileInvalid",
		Reason:              "MachineFileInvalid",
		Action:              "VerifyMachineFile",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Machine File is invalid in license secret. Please contact kubeslice support team.",
	},
	"LicenseKeyInvalid": {
		Name:                "LicenseKeyInvalid",
		Reason:              "LicenseKeyInvalid",
		Action:              "DecryptMachineFile",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "License Key is invalid in license secret. Please contact kubeslice support team.",
	},
	"LicenseExpired": {
		Name:                "LicenseExpired",
		Reason:              "LicenseExpired",
		Action:              "ValidateLicense",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "License Expired, please contact kubeslice support team to get it renewed!",
	},
	"LicenseExpiredGracePeriodOn": {
		Name:                "LicenseExpiredGracePeriodOn",
		Reason:              "LicenseExpiredGracePeriodOn",
		Action:              "ValidateLicense",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "License Expired, grace period is on, please contact kubeslice support team to get it renewed!",
	},
	"MachineFingerPrintErr": {
		Name:                "MachineFingerPrintErr",
		Reason:              "MachineFingerPrintErr",
		Action:              "GetMachineFingerPrint",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Unable to fetch MachineFingerPrint. Please look at the kubeslice-controller logs for more details.",
	},
	"GotMachineFingerPrint": {
		Name:                "GotMachineFingerPrint",
		Reason:              "GotMachineFingerPrint",
		Action:              "GetMachineFingerPrint",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Got MachineFingerPrint successfully",
	},
	"ConfigMapErr": {
		Name:                "ConfigMapErr",
		Reason:              "ConfigMapErr",
		Action:              "GetConfigMap",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Unable to validate license keys from configmap. Please contact kubeslice support team",
	},
	"GotConfigMap": {
		Name:                "GotConfigMap",
		Reason:              "GotConfigMap",
		Action:              "GetConfigMap",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Got ConfigMap and kubeslice-license public keys successfully.",
	},
	"LicenseProxyUnreachable": {
		Name:                "LicenseProxyUnreachable",
		Reason:              "LicenseProxyUnreachable",
		Action:              "LicenseProxy",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Failed to get response from license proxy for automatic license creation. Please contact Avesha to obtain licernse manually.",
	},
	"LicenseDeployError": {
		Name:                "LicenseDeployError",
		Reason:              "LicenseDeployError",
		Action:              "LicenseDeploy",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Failed to deploy license secret.",
	},
	"LicenseDeploySuccess": {
		Name:                "LicenseDeploySuccess",
		Reason:              "LicenseDeploySuccess",
		Action:              "LicenseDeploy",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Successfully fetched license data & deployed license secret.",
	},
	"ClusterMetadataCollectionFailed": {
		Name:                "ClusterMetadataCollectionFailed",
		Reason:              "ClusterMetadataCollectionFailed",
		Action:              "CollectClusterMetadata",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Failed to collect cluster metadata for cluster creation.",
	},
	"ClusterMetadataCollectionSuccess": {
		Name:                "ClusterMetadataCollectionSuccess",
		Reason:              "ClusterMetadataCollectionSuccess",
		Action:              "CollectClusterMetadata",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Successfully collected cluster metadata for license creation.",
	},
	"LicenseDataFetchError": {
		Name:                "LicenseDataFetchError",
		Reason:              "LicenseDataFetchError",
		Action:              "LicenseDataFetch",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Failed to fetch license data from license proxy.",
	},
	"LicenseDataFetchSuccess": {
		Name:                "LicenseDataFetchSuccess",
		Reason:              "LicenseDataFetchSuccess",
		Action:              "LicenseDataFetch",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Successfully fetched license data from license proxy.",
	},
	"LicenseSecretCreationFailed": {
		Name:                "LicenseSecretCreationFailed",
		Reason:              "LicenseSecretCreationFailed",
		Action:              "LicenseSecretCreation",
		Type:                events.EventTypeWarning,
		ReportingController: "kubeslice-controller",
		Message:             "Failed to create license secret.",
	},
	"LicenseSecretCreationSuccess": {
		Name:                "LicenseSecretCreationSuccess",
		Reason:              "LicenseSecretCreationSuccess",
		Action:              "LicenseSecretCreation",
		Type:                events.EventTypeNormal,
		ReportingController: "kubeslice-controller",
		Message:             "Successfully created license secret.",
	},
	"ProjectDeleted": {
		Name:                "ProjectDeleted",
		Reason:              "ProjectDeleted",
		Action:              "DeleteProject",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Project got deleted.",
	},
	"ProjectDeletionFailed": {
		Name:                "ProjectDeletionFailed",
		Reason:              "ProjectDeletionFailed",
		Action:              "DeleteProject",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Project deletion failed.",
	},
	"ClusterDeleted": {
		Name:                "ClusterDeleted",
		Reason:              "ClusterDeleted",
		Action:              "DeleteCluster",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Cluster got deleted.",
	},
	"ClusterDeletionFailed": {
		Name:                "ClusterDeletionFailed",
		Reason:              "ClusterDeletionFailed",
		Action:              "DeleteCluster",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Cluster deletion failed.",
	},
	"SliceConfigDeleted": {
		Name:                "SliceConfigDeleted",
		Reason:              "SliceConfigDeleted",
		Action:              "DeleteSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice config got deleted.",
	},
	"SliceConfigDeletionFailed": {
		Name:                "SliceConfigDeletionFailed",
		Reason:              "SliceConfigDeletionFailed",
		Action:              "DeleteSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice config deletion failed.",
	},
	"ServiceExportConfigDeleted": {
		Name:                "ServiceExportConfigDeleted",
		Reason:              "ServiceExportConfigDeleted",
		Action:              "DeleteServiceExportConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service export config got deleted.",
	},
	"ServiceExportConfigDeletionFailed": {
		Name:                "ServiceExportConfigDeletionFailed",
		Reason:              "ServiceExportConfigDeletionFailed",
		Action:              "DeleteServiceExportConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service export config deletion failed.",
	},
	"SliceQoSConfigDeleted": {
		Name:                "SliceQoSConfigDeleted",
		Reason:              "SliceQoSConfigDeleted",
		Action:              "DeleteSliceQoSConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice QoS config got deleted.",
	},
	"SliceQoSConfigDeletionFailed": {
		Name:                "SliceQoSConfigDeletionFailed",
		Reason:              "SliceQoSConfigDeletionFailed",
		Action:              "DeleteSliceQoSConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice QoS config deletion failed.",
	},
	"SecretDeleted": {
		Name:                "SecretDeleted",
		Reason:              "SecretDeleted",
		Action:              "DeleteSecret",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Secret got deleted.",
	},
	"SecretDeletionFailed": {
		Name:                "SecretDeletionFailed",
		Reason:              "SecretDeletionFailed",
		Action:              "DeleteSecret",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Secret deletion failed.",
	},
	"NamespaceCreated": {
		Name:                "NamespaceCreated",
		Reason:              "NamespaceCreated",
		Action:              "CreateNamespace",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Namespace got created.",
	},
	"NamespaceCreationFailed": {
		Name:                "NamespaceCreationFailed",
		Reason:              "NamespaceCreationFailed",
		Action:              "CreateNamespace",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Namespace creation failed.",
	},
	"NamespaceDeleted": {
		Name:                "NamespaceDeleted",
		Reason:              "NamespaceDeleted",
		Action:              "DeleteNamespace",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Namespace got deleted.",
	},
	"NamespaceDeletionFailed": {
		Name:                "NamespaceDeletionFailed",
		Reason:              "NamespaceDeletionFailed",
		Action:              "DeleteNamespace",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Namespace deletion failed.",
	},
	"WorkerClusterRoleCreated": {
		Name:                "WorkerClusterRoleCreated",
		Reason:              "WorkerClusterRoleCreated",
		Action:              "CreateWorkerClusterRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker cluster role got created.",
	},
	"WorkerClusterRoleCreationFailed": {
		Name:                "WorkerClusterRoleCreationFailed",
		Reason:              "WorkerClusterRoleCreationFailed",
		Action:              "CreateWorkerClusterRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker cluster role creation failed.",
	},
	"WorkerClusterRoleUpdated": {
		Name:                "WorkerClusterRoleUpdated",
		Reason:              "WorkerClusterRoleUpdated",
		Action:              "UpdateWorkerClusterRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker cluster role got updated.",
	},
	"WorkerClusterRoleUpdateFailed": {
		Name:                "WorkerClusterRoleUpdateFailed",
		Reason:              "WorkerClusterRoleUpdateFailed",
		Action:              "UpdateWorkerClusterRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker cluster role update failed.",
	},
	"ReadOnlyRoleCreated": {
		Name:                "ReadOnlyRoleCreated",
		Reason:              "ReadOnlyRoleCreated",
		Action:              "CreateReadOnlyRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Read only role got created.",
	},
	"ReadOnlyRoleCreationFailed": {
		Name:                "ReadOnlyRoleCreationFailed",
		Reason:              "ReadOnlyRoleCreationFailed",
		Action:              "CreateReadOnlyRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Read only role creation failed.",
	},
	"ReadOnlyRoleUpdated": {
		Name:                "ReadOnlyRoleUpdated",
		Reason:              "ReadOnlyRoleUpdated",
		Action:              "UpdateReadOnlyRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Read only role got updated.",
	},
	"ReadOnlyRoleUpdateFailed": {
		Name:                "ReadOnlyRoleUpdateFailed",
		Reason:              "ReadOnlyRoleUpdateFailed",
		Action:              "UpdateReadOnlyRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Read only role update failed.",
	},
	"ReadWriteRoleCreated": {
		Name:                "ReadWriteRoleCreated",
		Reason:              "ReadWriteRoleCreated",
		Action:              "CreateReadWriteRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Read write role got created.",
	},
	"ReadWriteRoleCreationFailed": {
		Name:                "ReadWriteRoleCreationFailed",
		Reason:              "ReadWriteRoleCreationFailed",
		Action:              "CreateReadWriteRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Read write role creation failed.",
	},
	"ReadWriteRoleUpdated": {
		Name:                "ReadWriteRoleUpdated",
		Reason:              "ReadWriteRoleUpdated",
		Action:              "UpdateReadWriteRole",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Read write role got updated.",
	},
	"ReadWriteRoleUpdateFailed": {
		Name:                "ReadWriteRoleUpdateFailed",
		Reason:              "ReadWriteRoleUpdateFailed",
		Action:              "UpdateReadWriteRole",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Read write role update failed.",
	},
	"ServiceAccountCreated": {
		Name:                "ServiceAccountCreated",
		Reason:              "ServiceAccountCreated",
		Action:              "CreateServiceAccount",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Service account got created.",
	},
	"ServiceAccountCreationFailed": {
		Name:                "ServiceAccountCreationFailed",
		Reason:              "ServiceAccountCreationFailed",
		Action:              "CreateServiceAccount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service account creation failed.",
	},
	"ServiceAccountSecretCreated": {
		Name:                "ServiceAccountSecretCreated",
		Reason:              "ServiceAccountSecretCreated",
		Action:              "CreateServiceAccountSecret",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Service account secret got created.",
	},
	"ServiceAccountSecretCreationFailed": {
		Name:                "ServiceAccountSecretCreationFailed",
		Reason:              "ServiceAccountSecretCreationFailed",
		Action:              "CreateServiceAccountSecret",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service account secret creation failed.",
	},
	"DefaultRoleBindingCreated": {
		Name:                "DefaultRoleBindingCreated",
		Reason:              "DefaultRoleBindingCreated",
		Action:              "CreateDefaultRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Default role binding got created.",
	},
	"DefaultRoleBindingCreationFailed": {
		Name:                "DefaultRoleBindingCreationFailed",
		Reason:              "DefaultRoleBindingCreationFailed",
		Action:              "CreateDefaultRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default role binding creation failed.",
	},
	"DefaultRoleBindingUpdated": {
		Name:                "DefaultRoleBindingUpdated",
		Reason:              "DefaultRoleBindingUpdated",
		Action:              "UpdateDefaultRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Default role binding got updated.",
	},
	"DefaultRoleBindingUpdateFailed": {
		Name:                "DefaultRoleBindingUpdateFailed",
		Reason:              "DefaultRoleBindingUpdateFailed",
		Action:              "UpdateDefaultRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default role binding update failed.",
	},
	"DefaultRoleBindingDeleted": {
		Name:                "DefaultRoleBindingDeleted",
		Reason:              "DefaultRoleBindingDeleted",
		Action:              "DeleteDefaultRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default role binding got deleted.",
	},
	"DefaultRoleBindingDeletionFailed": {
		Name:                "DefaultRoleBindingDeletionFailed",
		Reason:              "DefaultRoleBindingDeletionFailed",
		Action:              "DeleteDefaultRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default role binding deletion failed.",
	},
	"InactiveRoleBindingDeleted": {
		Name:                "InactiveRoleBindingDeleted",
		Reason:              "InactiveRoleBindingDeleted",
		Action:              "DeleteInactiveRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Inactive role binding got deleted.",
	},
	"InactiveRoleBindingDeletionFailed": {
		Name:                "InactiveRoleBindingDeletionFailed",
		Reason:              "InactiveRoleBindingDeletionFailed",
		Action:              "DeleteInactiveRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Inactive role binding deletion failed.",
	},
	"InactiveServiceAccountDeleted": {
		Name:                "InactiveServiceAccountDeleted",
		Reason:              "InactiveServiceAccountDeleted",
		Action:              "DeleteInactiveServiceAccount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Inactive service account got deleted.",
	},
	"InactiveServiceAccountDeletionFailed": {
		Name:                "InactiveServiceAccountDeletionFailed",
		Reason:              "InactiveServiceAccountDeletionFailed",
		Action:              "DeleteInactiveServiceAccount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Inactive service account deletion failed.",
	},
	"ServiceAccountDeleted": {
		Name:                "ServiceAccountDeleted",
		Reason:              "ServiceAccountDeleted",
		Action:              "DeleteServiceAccount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service account got deleted.",
	},
	"ServiceAccountDeletionFailed": {
		Name:                "ServiceAccountDeletionFailed",
		Reason:              "ServiceAccountDeletionFailed",
		Action:              "DeleteServiceAccount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Service account deletion failed.",
	},
	"WorkerServiceImportDeletedForcefully": {
		Name:                "WorkerServiceImportDeletedForcefully",
		Reason:              "WorkerServiceImportDeletedForcefully",
		Action:              "DeleteWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import got deleted forcefully.",
	},
	"WorkerServiceImportRecreationFailed": {
		Name:                "WorkerServiceImportRecreationFailed",
		Reason:              "WorkerServiceImportRecreationFailed",
		Action:              "CreateWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import recreation failed after forceful deletion.",
	},
	"WorkerServiceImportRecreated": {
		Name:                "WorkerServiceImportRecreated",
		Reason:              "WorkerServiceImportRecreated",
		Action:              "CreateWorkerServiceImport",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker service import got recreated after forceful deletion.",
	},
	"WorkerServiceImportCreationFailed": {
		Name:                "WorkerServiceImportCreationFailed",
		Reason:              "WorkerServiceImportCreationFailed",
		Action:              "CreateWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import creation failed.",
	},
	"WorkerServiceImportCreated": {
		Name:                "WorkerServiceImportCreated",
		Reason:              "WorkerServiceImportCreated",
		Action:              "CreateWorkerServiceImport",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker service import got created.",
	},
	"WorkerServiceImportUpdateFailed": {
		Name:                "WorkerServiceImportUpdateFailed",
		Reason:              "WorkerServiceImportUpdateFailed",
		Action:              "UpdateWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import update failed.",
	},
	"WorkerServiceImportUpdated": {
		Name:                "WorkerServiceImportUpdated",
		Reason:              "WorkerServiceImportUpdated",
		Action:              "UpdateWorkerServiceImport",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker service import got updated.",
	},
	"WorkerServiceImportDeleted": {
		Name:                "WorkerServiceImportDeleted",
		Reason:              "WorkerServiceImportDeleted",
		Action:              "DeleteWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import got deleted.",
	},
	"WorkerServiceImportDeletionFailed": {
		Name:                "WorkerServiceImportDeletionFailed",
		Reason:              "WorkerServiceImportDeletionFailed",
		Action:              "DeleteWorkerServiceImport",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker service import deletion failed.",
	},
	"WorkerSliceConfigDeletedForcefully": {
		Name:                "WorkerSliceConfigDeletedForcefully",
		Reason:              "WorkerSliceConfigDeletedForcefully",
		Action:              "DeleteWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config got deleted forcefully.",
	},
	"WorkerSliceConfigRecreationFailed": {
		Name:                "WorkerSliceConfigRecreationFailed",
		Reason:              "WorkerSliceConfigRecreationFailed",
		Action:              "CreateWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config recreation failed after forceful deletion.",
	},
	"WorkerSliceConfigRecreated": {
		Name:                "WorkerSliceConfigRecreated",
		Reason:              "WorkerSliceConfigRecreated",
		Action:              "CreateWorkerSliceConfig",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice config got recreated after forceful deletion.",
	},
	"WorkerSliceConfigCreationFailed": {
		Name:                "WorkerSliceConfigCreationFailed",
		Reason:              "WorkerSliceConfigCreationFailed",
		Action:              "CreateWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config creation failed.",
	},
	"WorkerSliceConfigCreated": {
		Name:                "WorkerSliceConfigCreated",
		Reason:              "WorkerSliceConfigCreated",
		Action:              "CreateWorkerSliceConfig",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice config got created.",
	},
	"WorkerSliceConfigUpdateFailed": {
		Name:                "WorkerSliceConfigUpdateFailed",
		Reason:              "WorkerSliceConfigUpdateFailed",
		Action:              "UpdateWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config update failed.",
	},
	"WorkerSliceConfigUpdated": {
		Name:                "WorkerSliceConfigUpdated",
		Reason:              "WorkerSliceConfigUpdated",
		Action:              "UpdateWorkerSliceConfig",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice config got updated.",
	},
	"WorkerSliceConfigDeleted": {
		Name:                "WorkerSliceConfigDeleted",
		Reason:              "WorkerSliceConfigDeleted",
		Action:              "DeleteWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config got deleted.",
	},
	"WorkerSliceConfigDeletionFailed": {
		Name:                "WorkerSliceConfigDeletionFailed",
		Reason:              "WorkerSliceConfigDeletionFailed",
		Action:              "DeleteWorkerSliceConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice config deletion failed.",
	},
	"WorkerSliceGatewayDeletedForcefully": {
		Name:                "WorkerSliceGatewayDeletedForcefully",
		Reason:              "WorkerSliceGatewayDeletedForcefully",
		Action:              "DeleteWorkerSliceGateway",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice gateway got deleted forcefully.",
	},
	"WorkerSliceGatewayRecreationFailed": {
		Name:                "WorkerSliceGatewayRecreationFailed",
		Reason:              "WorkerSliceGatewayRecreationFailed",
		Action:              "CreateWorkerSliceGateway",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice gateway recreation failed after forceful deletion.",
	},
	"WorkerSliceGatewayRecreated": {
		Name:                "WorkerSliceGatewayRecreated",
		Reason:              "WorkerSliceGatewayRecreated",
		Action:              "CreateWorkerSliceGateway",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice gateway got recreated after forceful deletion.",
	},
	"WorkerSliceGatewayDeletionFailed": {
		Name:                "WorkerSliceGatewayDeletionFailed",
		Reason:              "WorkerSliceGatewayDeletionFailed",
		Action:              "DeleteWorkerSliceGateway",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice gateway deletion failed.",
	},
	"WorkerSliceGatewayDeleted": {
		Name:                "WorkerSliceGatewayDeleted",
		Reason:              "WorkerSliceGatewayDeleted",
		Action:              "DeleteWorkerSliceGateway",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice gateway got deleted.",
	},
	"WorkerSliceGatewayCreationFailed": {
		Name:                "WorkerSliceGatewayCreationFailed",
		Reason:              "WorkerSliceGatewayCreationFailed",
		Action:              "CreateWorkerSliceGateway",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice gateway creation failed.",
	},
	"WorkerSliceGatewayCreated": {
		Name:                "WorkerSliceGatewayCreated",
		Reason:              "WorkerSliceGatewayCreated",
		Action:              "CreateWorkerSliceGateway",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice gateway got created.",
	},
	"SliceGatewayJobCreationFailed": {
		Name:                "SliceGatewayJobCreationFailed",
		Reason:              "SliceGatewayJobCreationFailed",
		Action:              "CreateSliceGatewayJob",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice gateway job creation failed.",
	},
	"SliceGatewayJobCreated": {
		Name:                "SliceGatewayJobCreated",
		Reason:              "SliceGatewayJobCreated",
		Action:              "CreateSliceGatewayJob",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice gateway job got created.",
	},
	"DefaultDeploymentSliceRoleTemplateCreationFailed": {
		Name:                "DefaultDeploymentSliceRoleTemplateCreationFailed",
		Reason:              "DefaultDeploymentSliceRoleTemplateCreationFailed",
		Action:              "CreateSliceRoleTemplate",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default deployment slice role template creation failed.",
	},
	"DefaultDeploymentSliceRoleTemplateCreated": {
		Name:                "DefaultDeploymentSliceRoleTemplateCreated",
		Reason:              "DefaultDeploymentSliceRoleTemplateCreated",
		Action:              "CreateSliceRoleTemplate",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Default deployment slice role template got created.",
	},
	"DefaultReaderSliceRoleTemplateCreationFailed": {
		Name:                "DefaultReaderSliceRoleTemplateCreationFailed",
		Reason:              "DefaultReaderSliceRoleTemplateCreationFailed",
		Action:              "CreateSliceRoleTemplate",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Default reader slice role template creation failed.",
	},
	"DefaultReaderSliceRoleTemplateCreated": {
		Name:                "DefaultReaderSliceRoleTemplateCreated",
		Reason:              "DefaultReaderSliceRoleTemplateCreated",
		Action:              "CreateSliceRoleTemplate",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Default reader slice role template got created.",
	},
	"SliceRoleTemplateDeletionFailed": {
		Name:                "SliceRoleTemplateDeletionFailed",
		Reason:              "SliceRoleTemplateDeletionFailed",
		Action:              "DeleteSliceRoleTemplate",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice role template deletion failed.",
	},
	"SliceRoleTemplateDeleted": {
		Name:                "SliceRoleTemplateDeleted",
		Reason:              "SliceRoleTemplateDeleted",
		Action:              "DeleteSliceRoleTemplate",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice role template got deleted.",
	},
	"SliceResourceQuotaCreationFailed": {
		Name:                "SliceResourceQuotaCreationFailed",
		Reason:              "SliceResourceQuotaCreationFailed",
		Action:              "CreateSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice resource quota creation failed while creating slice config.",
	},
	"SliceResourceQuotaCreatedOnSliceConfigCreation": {
		Name:                "SliceResourceQuotaCreatedOnSliceConfigCreation",
		Reason:              "SliceResourceQuotaCreatedOnSliceConfigCreation",
		Action:              "CreateSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice resource quota got created while creating slice config.",
	},
	"SliceResourceQuotaDeletionFailed": {
		Name:                "SliceResourceQuotaDeletionFailed",
		Reason:              "SliceResourceQuotaDeletionFailed",
		Action:              "DeleteSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice resource quota deletion failed.",
	},
	"SliceResourceQuotaDeleted": {
		Name:                "SliceResourceQuotaDeleted",
		Reason:              "SliceResourceQuotaDeleted",
		Action:              "DeleteSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice resource quota got deleted.",
	},
	"SliceResourceQuotaRecreationFailed": {
		Name:                "SliceResourceQuotaRecreationFailed",
		Reason:              "SliceResourceQuotaRecreationFailed",
		Action:              "CreateSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice resource quota recreation failed after forceful deletion.",
	},
	"SliceResourceQuotaRecreated": {
		Name:                "SliceResourceQuotaRecreated",
		Reason:              "SliceResourceQuotaRecreated",
		Action:              "CreateSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice resource quota got recreated after forceful deletion.",
	},
	"SetSliceConfigAsOwnerOfSliceResourceQuotaFailed": {
		Name:                "SetSliceConfigAsOwnerOfSliceResourceQuotaFailed",
		Reason:              "SetSliceConfigAsOwnerOfSliceResourceQuotaFailed",
		Action:              "SetSliceConfigAsOwnerOfSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Failed to set slice config as owner of slice resource quota config.",
	},
	"SetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded": {
		Name:                "SetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded",
		Reason:              "SetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded",
		Action:              "SetSliceConfigAsOwnerOfSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Successfully set slice config as owner of slice resource quota config.",
	},
	"SliceResourceQuotaCreated": {
		Name:                "SliceResourceQuotaCreated",
		Reason:              "SliceResourceQuotaCreated",
		Action:              "CreateSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice resource quota config got created successfully.",
	},
	"SliceResourceQuotaUpdated": {
		Name:                "SliceResourceQuotaUpdated",
		Reason:              "SliceResourceQuotaUpdated",
		Action:              "UpdateSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice resource quota config got updated successfully.",
	},
	"AllRQSpecificationViolationMetricsResetSuccess": {
		Name:                "AllRQSpecificationViolationMetricsResetSuccess",
		Reason:              "AllRQSpecificationViolationMetricsResetSuccess",
		Action:              "ResetResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "All resource quota specifications and violations metrics got reset successfully.",
	},
	"SliceRQSpecificationViolationMetricsResetSuccess": {
		Name:                "SliceRQSpecificationViolationMetricsResetSuccess",
		Reason:              "SliceRQSpecificationViolationMetricsResetSuccess",
		Action:              "ResetResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "All slice level resource quota specifications and violations metrics got reset successfully.",
	},
	"ClusterRQSpecificationViolationMetricsResetSuccess": {
		Name:                "ClusterRQSpecificationViolationMetricsResetSuccess",
		Reason:              "ClusterRQSpecificationViolationMetricsResetSuccess",
		Action:              "ResetResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "All cluster level resource quota specifications and violations metrics got reset successfully.",
	},
	"OutdatedNamespaceRQSpecificationViolationMetricsResetSuccess": {
		Name:                "OutdatedNamespaceRQSpecificationViolationMetricsResetSuccess",
		Reason:              "OutdatedNamespaceRQSpecificationViolationMetricsResetSuccess",
		Action:              "ResetResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "All outdated namespace level resource quota specifications and violations metrics got reset successfully.",
	},
	"OutdatedClusterRQSpecificationViolationMetricsResetSuccess": {
		Name:                "OutdatedClusterRQSpecificationViolationMetricsResetSuccess",
		Reason:              "OutdatedClusterRQSpecificationViolationMetricsResetSuccess",
		Action:              "ResetResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "All outdated cluster level resource quota specifications and violations metrics got reset successfully.",
	},
	"SliceNodeAffinityDeletionFailed": {
		Name:                "SliceNodeAffinityDeletionFailed",
		Reason:              "SliceNodeAffinityDeletionFailed",
		Action:              "DeleteSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice node affinity deletion failed.",
	},
	"SliceNodeAffinityDeleted": {
		Name:                "SliceNodeAffinityDeleted",
		Reason:              "SliceNodeAffinityDeleted",
		Action:              "DeleteSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice node affinity got deleted.",
	},
	"SetSliceConfigAsOwnerOfSliceNodeAffinityFailed": {
		Name:                "SetSliceConfigAsOwnerOfSliceNodeAffinityFailed",
		Reason:              "SetSliceConfigAsOwnerOfSliceNodeAffinityFailed",
		Action:              "SetSliceConfigAsOwnerOfSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Failed to set slice config as owner of slice node affinity.",
	},
	"SetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded": {
		Name:                "SetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded",
		Reason:              "SetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded",
		Action:              "SetSliceConfigAsOwnerOfSliceNodeAffinity",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Successfully set slice config as owner of slice node affinity.",
	},
	"SliceRoleBindingDeletingFailed": {
		Name:                "SliceRoleBindingDeletingFailed",
		Reason:              "SliceRoleBindingDeletingFailed",
		Action:              "DeleteSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Slice role binding deletion failed.",
	},
	"SliceRoleBindingDeleted": {
		Name:                "SliceRoleBindingDeleted",
		Reason:              "SliceRoleBindingDeleted",
		Action:              "DeleteSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Slice role binding got deleted.",
	},
	"SetSliceConfigAsOwnerOfSliceRoleBindingFailed": {
		Name:                "SetSliceConfigAsOwnerOfSliceRoleBindingFailed",
		Reason:              "SetSliceConfigAsOwnerOfSliceRoleBindingFailed",
		Action:              "SetSliceConfigAsOwnerOfSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Failed to set slice config as owner of slice role binding.",
	},
	"SetSliceConfigAsOwnerOfSliceRoleBindingSucceeded": {
		Name:                "SetSliceConfigAsOwnerOfSliceRoleBindingSucceeded",
		Reason:              "SetSliceConfigAsOwnerOfSliceRoleBindingSucceeded",
		Action:              "SetSliceConfigAsOwnerOfSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Successfully set slice config as owner of slice role binding.",
	},
	"WorkerSliceRoleBindingReconciliationSuccess": {
		Name:                "WorkerSliceRoleBindingReconciliationSuccess",
		Reason:              "WorkerSliceRoleBindingReconciliationSuccess",
		Action:              "ReconcileWorkerSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Reconciliation of worker slice role binding is successful due to the change in slice role template.",
	},
	"WorkerSliceRoleBindingDeletedForcefully": {
		Name:                "WorkerSliceRoleBindingDeletedForcefully",
		Reason:              "WorkerSliceRoleBindingDeletedForcefully",
		Action:              "DeleteWorkerSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice role binding got deleted forcefully.",
	},
	"WorkerSliceRoleBindingRecreationFailed": {
		Name:                "WorkerSliceRoleBindingRecreationFailed",
		Reason:              "WorkerSliceRoleBindingRecreationFailed",
		Action:              "CreateWorkerSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice role binding recreation failed after forceful deletion.",
	},
	"WorkerSliceRoleBindingRecreated": {
		Name:                "WorkerSliceRoleBindingRecreated",
		Reason:              "WorkerSliceRoleBindingRecreated",
		Action:              "CreateWorkerSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice role binding got recreated after forceful deletion.",
	},
	"WorkerSliceRoleBindingCreationFailed": {
		Name:                "WorkerSliceRoleBindingCreationFailed",
		Reason:              "WorkerSliceRoleBindingCreationFailed",
		Action:              "CreateWorkerSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice role binding creation failed.",
	},
	"WorkerSliceRoleBindingCreated": {
		Name:                "WorkerSliceRoleBindingCreated",
		Reason:              "WorkerSliceRoleBindingCreated",
		Action:              "CreateWorkerSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice role binding got created successfully.",
	},
	"WorkerSliceRoleBindingUpdateFailed": {
		Name:                "WorkerSliceRoleBindingUpdateFailed",
		Reason:              "WorkerSliceRoleBindingUpdateFailed",
		Action:              "UpdateWorkerSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice role binding update failed.",
	},
	"WorkerSliceRoleBindingUpdated": {
		Name:                "WorkerSliceRoleBindingUpdated",
		Reason:              "WorkerSliceRoleBindingUpdated",
		Action:              "UpdateWorkerSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice role binding got updated successfully.",
	},
	"WorkerSliceRoleBindingDeletionFailed": {
		Name:                "WorkerSliceRoleBindingDeletionFailed",
		Reason:              "WorkerSliceRoleBindingDeletionFailed",
		Action:              "DeleteWorkerSliceRoleBinding",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice role binding deletion failed.",
	},
	"WorkerSliceRoleBindingDeleted": {
		Name:                "WorkerSliceRoleBindingDeleted",
		Reason:              "WorkerSliceRoleBindingDeleted",
		Action:              "DeleteWorkerSliceRoleBinding",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice role binding got deleted successfully.",
	},
	"WorkerSliceNodeAffinityDeletedForcefully": {
		Name:                "WorkerSliceNodeAffinityDeletedForcefully",
		Reason:              "WorkerSliceNodeAffinityDeletedForcefully",
		Action:              "DeleteWorkerSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice node affinity got deleted forcefully.",
	},
	"WorkerSliceNodeAffinityRecreationFailed": {
		Name:                "WorkerSliceNodeAffinityRecreationFailed",
		Reason:              "WorkerSliceNodeAffinityRecreationFailed",
		Action:              "CreateWorkerSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice node affinity recreation failed after forceful deletion.",
	},
	"WorkerSliceNodeAffinityRecreated": {
		Name:                "WorkerSliceNodeAffinityRecreated",
		Reason:              "WorkerSliceNodeAffinityRecreated",
		Action:              "CreateWorkerSliceNodeAffinity",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice node affinity got recreated after forceful deletion.",
	},
	"NodeAffinityRilesExpansionFailed": {
		Name:                "NodeAffinityRilesExpansionFailed",
		Reason:              "NodeAffinityRilesExpansionFailed",
		Action:              "ExpandNodeAffinityRules",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Node affinity rules expansion failed.",
	},
	"SliceNodeAffinityConfigDeepCopyFailed": {
		Name:                "SliceNodeAffinityConfigDeepCopyFailed",
		Reason:              "SliceNodeAffinityConfigDeepCopyFailed",
		Action:              "DeepCopySliceNodeAffinityConfig",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Deep copy of slice node affinity configuration got failed.",
	},
	"WorkerSliceNodeAffinityCreationFailed": {
		Name:                "WorkerSliceNodeAffinityCreationFailed",
		Reason:              "WorkerSliceNodeAffinityCreationFailed",
		Action:              "CreateWorkerSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice node affinity creation failed.",
	},
	"WorkerSliceNodeAffinityCreated": {
		Name:                "WorkerSliceNodeAffinityCreated",
		Reason:              "WorkerSliceNodeAffinityCreated",
		Action:              "CreateWorkerSliceNodeAffinity",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice node affinity got created successfully.",
	},
	"WorkerSliceNodeAffinityUpdateFailed": {
		Name:                "WorkerSliceNodeAffinityUpdateFailed",
		Reason:              "WorkerSliceNodeAffinityUpdateFailed",
		Action:              "UpdateWorkerSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice node affinity update failed.",
	},
	"WorkerSliceNodeAffinityUpdated": {
		Name:                "WorkerSliceNodeAffinityUpdated",
		Reason:              "WorkerSliceNodeAffinityUpdated",
		Action:              "UpdateWorkerSliceNodeAffinity",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice node affinity got updated successfully.",
	},
	"WorkerSliceNodeAffinityDeletionFailed": {
		Name:                "WorkerSliceNodeAffinityDeletionFailed",
		Reason:              "WorkerSliceNodeAffinityDeletionFailed",
		Action:              "DeleteWorkerSliceNodeAffinity",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice node affinity deletion failed.",
	},
	"WorkerSliceNodeAffinityDeleted": {
		Name:                "WorkerSliceNodeAffinityDeleted",
		Reason:              "WorkerSliceNodeAffinityDeleted",
		Action:              "DeleteWorkerSliceNodeAffinity",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice node affinity got deleted successfully.",
	},
	"WorkerSliceResourceQuotaDeletedForcefully": {
		Name:                "WorkerSliceResourceQuotaDeletedForcefully",
		Reason:              "WorkerSliceResourceQuotaDeletedForcefully",
		Action:              "DeleteWorkerSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice resource quota got deleted forcefully.",
	},
	"WorkerSliceResourceQuotaRecreationFailed": {
		Name:                "WorkerSliceResourceQuotaRecreationFailed",
		Reason:              "WorkerSliceResourceQuotaRecreationFailed",
		Action:              "CreateWorkerSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice resource quota recreation failed after forceful deletion.",
	},
	"WorkerSliceResourceQuotaRecreated": {
		Name:                "WorkerSliceResourceQuotaRecreated",
		Reason:              "WorkerSliceResourceQuotaRecreated",
		Action:              "CreateWorkerSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice resource quota got recreated after forceful deletion.",
	},
	"OffBoardedNamespaceUtilizationMetricsReset": {
		Name:                "OffBoardedNamespaceUtilizationMetricsReset",
		Reason:              "OffBoardedNamespaceUtilizationMetricsReset",
		Action:              "ResetOffBoardedNamespaceUtilizationMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Utilization metrics of off-boarded namespaces got reset successfully.",
	},
	"ResourceQuotaMetricsPopulated": {
		Name:                "ResourceQuotaMetricsPopulated",
		Reason:              "ResourceQuotaMetricsPopulated",
		Action:              "PopulateResourceQuotaMetrics",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Resource quota metrics got populated successfully.",
	},
	"ClusterCPULimitViolated": {
		Name:                "ClusterCPULimitViolated",
		Reason:              "ClusterCPULimitViolated",
		Action:              "ViolateClusterCPULimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU limit is violated at cluster level.",
	},
	"ClusterMemoryLimitViolated": {
		Name:                "ClusterMemoryLimitViolated",
		Reason:              "ClusterMemoryLimitViolated",
		Action:              "ViolateClusterMemoryLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory limit is violated at cluster level.",
	},
	"ClusterPodCountViolated": {
		Name:                "ClusterPodCountViolated",
		Reason:              "ClusterPodCountViolated",
		Action:              "ViolateClusterPodCount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Pod count is violated at cluster level.",
	},
	"ClusterEphemeralStorageLimitViolated": {
		Name:                "ClusterEphemeralStorageLimitViolated",
		Reason:              "ClusterEphemeralStorageLimitViolated",
		Action:              "ViolateClusterEphemeralStorageLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage limit is violated at cluster level.",
	},
	"ClusterCPURequestViolated": {
		Name:                "ClusterCPURequestViolated",
		Reason:              "ClusterCPURequestViolated",
		Action:              "ViolateClusterCPURequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU request is violated at cluster level.",
	},
	"ClusterMemoryRequestViolated": {
		Name:                "ClusterMemoryRequestViolated",
		Reason:              "ClusterMemoryRequestViolated",
		Action:              "ViolateClusterMemoryRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory request is violated at cluster level.",
	},
	"ClusterEphemeralStorageRequestViolated": {
		Name:                "ClusterEphemeralStorageRequestViolated",
		Reason:              "ClusterEphemeralStorageRequestViolated",
		Action:              "ViolateClusterEphemeralStorageRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage request is violated at cluster level.",
	},
	"NamespaceCPULimitViolated": {
		Name:                "NamespaceCPULimitViolated",
		Reason:              "NamespaceCPULimitViolated",
		Action:              "ViolateNamespaceCPULimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU limit is violated at namespace level.",
	},
	"NamespaceMemoryLimitViolated": {
		Name:                "NamespaceMemoryLimitViolated",
		Reason:              "NamespaceMemoryLimitViolated",
		Action:              "ViolateNamespaceMemoryLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory limit is violated at namespace level.",
	},
	"NamespacePodCountViolated": {
		Name:                "NamespacePodCountViolated",
		Reason:              "NamespacePodCountViolated",
		Action:              "ViolateNamespacePodCount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Pod count is violated at namespace level.",
	},
	"NamespaceEphemeralStorageLimitViolated": {
		Name:                "NamespaceEphemeralStorageLimitViolated",
		Reason:              "NamespaceEphemeralStorageLimitViolated",
		Action:              "ViolateNamespaceEphemeralStorageLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage limit is violated at namespace level.",
	},
	"NamespaceCPURequestViolated": {
		Name:                "NamespaceCPURequestViolated",
		Reason:              "NamespaceCPURequestViolated",
		Action:              "ViolateNamespaceCPURequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU request is violated at namespace level.",
	},
	"NamespaceMemoryRequestViolated": {
		Name:                "NamespaceMemoryRequestViolated",
		Reason:              "NamespaceMemoryRequestViolated",
		Action:              "ViolateNamespaceMemoryRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory request is violated at namespace level.",
	},
	"NamespaceEphemeralStorageRequestViolated": {
		Name:                "NamespaceEphemeralStorageRequestViolated",
		Reason:              "NamespaceEphemeralStorageRequestViolated",
		Action:              "ViolateNamespaceEphemeralStorageRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage request is violated at namespace level.",
	},
	"SliceCPULimitViolated": {
		Name:                "SliceCPULimitViolated",
		Reason:              "SliceCPULimitViolated",
		Action:              "ViolateSliceCPULimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU limit is violated at slice level.",
	},
	"SliceMemoryLimitViolated": {
		Name:                "SliceMemoryLimitViolated",
		Reason:              "SliceMemoryLimitViolated",
		Action:              "ViolateSliceMemoryLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory limit is violated at slice level.",
	},
	"SlicePodCountViolated": {
		Name:                "SlicePodCountViolated",
		Reason:              "SlicePodCountViolated",
		Action:              "ViolateSlicePodCount",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Pod count is violated at slice level.",
	},
	"SliceEphemeralStorageLimitViolated": {
		Name:                "SliceEphemeralStorageLimitViolated",
		Reason:              "SliceEphemeralStorageLimitViolated",
		Action:              "ViolateSliceEphemeralStorageLimit",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage limit is violated at slice level.",
	},
	"SliceCPURequestViolated": {
		Name:                "SliceCPURequestViolated",
		Reason:              "SliceCPURequestViolated",
		Action:              "ViolateSliceCPURequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "CPU request is violated at slice level.",
	},
	"SliceMemoryRequestViolated": {
		Name:                "SliceMemoryRequestViolated",
		Reason:              "SliceMemoryRequestViolated",
		Action:              "ViolateSliceMemoryRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Memory request is violated at slice level.",
	},
	"SliceEphemeralStorageRequestViolated": {
		Name:                "SliceEphemeralStorageRequestViolated",
		Reason:              "SliceEphemeralStorageRequestViolated",
		Action:              "ViolateSliceEphemeralStorageRequest",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Ephemeral storage request is violated at slice level.",
	},
	"WorkerSliceResourceQuotaCreationFailed": {
		Name:                "WorkerSliceResourceQuotaCreationFailed",
		Reason:              "WorkerSliceResourceQuotaCreationFailed",
		Action:              "CreateWorkerSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice resource quota creation failed.",
	},
	"WorkerSliceResourceQuotaCreated": {
		Name:                "WorkerSliceResourceQuotaCreated",
		Reason:              "WorkerSliceResourceQuotaCreated",
		Action:              "CreateWorkerSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice resource quota got created successfully.",
	},
	"WorkerSliceResourceQuotaUpdateFailed": {
		Name:                "WorkerSliceResourceQuotaUpdateFailed",
		Reason:              "WorkerSliceResourceQuotaUpdateFailed",
		Action:              "UpdateWorkerSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice resource quota update failed.",
	},
	"WorkerSliceResourceQuotaUpdated": {
		Name:                "WorkerSliceResourceQuotaUpdated",
		Reason:              "WorkerSliceResourceQuotaUpdated",
		Action:              "UpdateWorkerSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice resource quota got updated successfully.",
	},
	"WorkerSliceResourceQuotaDeletionFailed": {
		Name:                "WorkerSliceResourceQuotaDeletionFailed",
		Reason:              "WorkerSliceResourceQuotaDeletionFailed",
		Action:              "DeleteWorkerSliceResourceQuota",
		Type:                events.EventTypeWarning,
		ReportingController: "controller",
		Message:             "Worker slice resource quota deletion failed.",
	},
	"WorkerSliceResourceQuotaDeleted": {
		Name:                "WorkerSliceResourceQuotaDeleted",
		Reason:              "WorkerSliceResourceQuotaDeleted",
		Action:              "DeleteWorkerSliceResourceQuota",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Worker slice resource quota got deleted successfully.",
	},
	"ClusterDeboardSuccess": {
		Name:                "ClusterDeboardSuccess",
		Reason:              "ClusterDeboardSuccess",
		Action:              "DEBOARD_CLUSTER",
		Type:                events.EventTypeNormal,
		ReportingController: "controller",
		Message:             "Cluster Deboard workflow was successful.",
	},
}

var (
	EventLicenseSecretNotFound                                        events.EventName = "LicenseSecretNotFound"
	EventMachineFileNotFound                                          events.EventName = "MachineFileNotFound"
	EventMachineFileInvalid                                           events.EventName = "MachineFileInvalid"
	EventLicenseKeyInvalid                                            events.EventName = "LicenseKeyInvalid"
	EventLicenseExpired                                               events.EventName = "LicenseExpired"
	EventLicenseExpiredGracePeriodOn                                  events.EventName = "LicenseExpiredGracePeriodOn"
	EventMachineFingerPrintErr                                        events.EventName = "MachineFingerPrintErr"
	EventGotMachineFingerPrint                                        events.EventName = "GotMachineFingerPrint"
	EventConfigMapErr                                                 events.EventName = "ConfigMapErr"
	EventGotConfigMap                                                 events.EventName = "GotConfigMap"
	EventLicenseProxyUnreachable                                      events.EventName = "LicenseProxyUnreachable"
	EventLicenseDeployError                                           events.EventName = "LicenseDeployError"
	EventLicenseDeploySuccess                                         events.EventName = "LicenseDeploySuccess"
	EventClusterMetadataCollectionFailed                              events.EventName = "ClusterMetadataCollectionFailed"
	EventClusterMetadataCollectionSuccess                             events.EventName = "ClusterMetadataCollectionSuccess"
	EventLicenseDataFetchError                                        events.EventName = "LicenseDataFetchError"
	EventLicenseDataFetchSuccess                                      events.EventName = "LicenseDataFetchSuccess"
	EventLicenseSecretCreationFailed                                  events.EventName = "LicenseSecretCreationFailed"
	EventLicenseSecretCreationSuccess                                 events.EventName = "LicenseSecretCreationSuccess"
	EventProjectDeleted                                               events.EventName = "ProjectDeleted"
	EventProjectDeletionFailed                                        events.EventName = "ProjectDeletionFailed"
	EventClusterDeleted                                               events.EventName = "ClusterDeleted"
	EventClusterDeletionFailed                                        events.EventName = "ClusterDeletionFailed"
	EventSliceConfigDeleted                                           events.EventName = "SliceConfigDeleted"
	EventSliceConfigDeletionFailed                                    events.EventName = "SliceConfigDeletionFailed"
	EventServiceExportConfigDeleted                                   events.EventName = "ServiceExportConfigDeleted"
	EventServiceExportConfigDeletionFailed                            events.EventName = "ServiceExportConfigDeletionFailed"
	EventSliceQoSConfigDeleted                                        events.EventName = "SliceQoSConfigDeleted"
	EventSliceQoSConfigDeletionFailed                                 events.EventName = "SliceQoSConfigDeletionFailed"
	EventSecretDeleted                                                events.EventName = "SecretDeleted"
	EventSecretDeletionFailed                                         events.EventName = "SecretDeletionFailed"
	EventNamespaceCreated                                             events.EventName = "NamespaceCreated"
	EventNamespaceCreationFailed                                      events.EventName = "NamespaceCreationFailed"
	EventNamespaceDeleted                                             events.EventName = "NamespaceDeleted"
	EventNamespaceDeletionFailed                                      events.EventName = "NamespaceDeletionFailed"
	EventWorkerClusterRoleCreated                                     events.EventName = "WorkerClusterRoleCreated"
	EventWorkerClusterRoleCreationFailed                              events.EventName = "WorkerClusterRoleCreationFailed"
	EventWorkerClusterRoleUpdated                                     events.EventName = "WorkerClusterRoleUpdated"
	EventWorkerClusterRoleUpdateFailed                                events.EventName = "WorkerClusterRoleUpdateFailed"
	EventReadOnlyRoleCreated                                          events.EventName = "ReadOnlyRoleCreated"
	EventReadOnlyRoleCreationFailed                                   events.EventName = "ReadOnlyRoleCreationFailed"
	EventReadOnlyRoleUpdated                                          events.EventName = "ReadOnlyRoleUpdated"
	EventReadOnlyRoleUpdateFailed                                     events.EventName = "ReadOnlyRoleUpdateFailed"
	EventReadWriteRoleCreated                                         events.EventName = "ReadWriteRoleCreated"
	EventReadWriteRoleCreationFailed                                  events.EventName = "ReadWriteRoleCreationFailed"
	EventReadWriteRoleUpdated                                         events.EventName = "ReadWriteRoleUpdated"
	EventReadWriteRoleUpdateFailed                                    events.EventName = "ReadWriteRoleUpdateFailed"
	EventServiceAccountCreated                                        events.EventName = "ServiceAccountCreated"
	EventServiceAccountCreationFailed                                 events.EventName = "ServiceAccountCreationFailed"
	EventServiceAccountSecretCreated                                  events.EventName = "ServiceAccountSecretCreated"
	EventServiceAccountSecretCreationFailed                           events.EventName = "ServiceAccountSecretCreationFailed"
	EventDefaultRoleBindingCreated                                    events.EventName = "DefaultRoleBindingCreated"
	EventDefaultRoleBindingCreationFailed                             events.EventName = "DefaultRoleBindingCreationFailed"
	EventDefaultRoleBindingUpdated                                    events.EventName = "DefaultRoleBindingUpdated"
	EventDefaultRoleBindingUpdateFailed                               events.EventName = "DefaultRoleBindingUpdateFailed"
	EventDefaultRoleBindingDeleted                                    events.EventName = "DefaultRoleBindingDeleted"
	EventDefaultRoleBindingDeletionFailed                             events.EventName = "DefaultRoleBindingDeletionFailed"
	EventInactiveRoleBindingDeleted                                   events.EventName = "InactiveRoleBindingDeleted"
	EventInactiveRoleBindingDeletionFailed                            events.EventName = "InactiveRoleBindingDeletionFailed"
	EventInactiveServiceAccountDeleted                                events.EventName = "InactiveServiceAccountDeleted"
	EventInactiveServiceAccountDeletionFailed                         events.EventName = "InactiveServiceAccountDeletionFailed"
	EventServiceAccountDeleted                                        events.EventName = "ServiceAccountDeleted"
	EventServiceAccountDeletionFailed                                 events.EventName = "ServiceAccountDeletionFailed"
	EventWorkerServiceImportDeletedForcefully                         events.EventName = "WorkerServiceImportDeletedForcefully"
	EventWorkerServiceImportRecreationFailed                          events.EventName = "WorkerServiceImportRecreationFailed"
	EventWorkerServiceImportRecreated                                 events.EventName = "WorkerServiceImportRecreated"
	EventWorkerServiceImportCreationFailed                            events.EventName = "WorkerServiceImportCreationFailed"
	EventWorkerServiceImportCreated                                   events.EventName = "WorkerServiceImportCreated"
	EventWorkerServiceImportUpdateFailed                              events.EventName = "WorkerServiceImportUpdateFailed"
	EventWorkerServiceImportUpdated                                   events.EventName = "WorkerServiceImportUpdated"
	EventWorkerServiceImportDeleted                                   events.EventName = "WorkerServiceImportDeleted"
	EventWorkerServiceImportDeletionFailed                            events.EventName = "WorkerServiceImportDeletionFailed"
	EventWorkerSliceConfigDeletedForcefully                           events.EventName = "WorkerSliceConfigDeletedForcefully"
	EventWorkerSliceConfigRecreationFailed                            events.EventName = "WorkerSliceConfigRecreationFailed"
	EventWorkerSliceConfigRecreated                                   events.EventName = "WorkerSliceConfigRecreated"
	EventWorkerSliceConfigCreationFailed                              events.EventName = "WorkerSliceConfigCreationFailed"
	EventWorkerSliceConfigCreated                                     events.EventName = "WorkerSliceConfigCreated"
	EventWorkerSliceConfigUpdateFailed                                events.EventName = "WorkerSliceConfigUpdateFailed"
	EventWorkerSliceConfigUpdated                                     events.EventName = "WorkerSliceConfigUpdated"
	EventWorkerSliceConfigDeleted                                     events.EventName = "WorkerSliceConfigDeleted"
	EventWorkerSliceConfigDeletionFailed                              events.EventName = "WorkerSliceConfigDeletionFailed"
	EventWorkerSliceGatewayDeletedForcefully                          events.EventName = "WorkerSliceGatewayDeletedForcefully"
	EventWorkerSliceGatewayRecreationFailed                           events.EventName = "WorkerSliceGatewayRecreationFailed"
	EventWorkerSliceGatewayRecreated                                  events.EventName = "WorkerSliceGatewayRecreated"
	EventWorkerSliceGatewayDeletionFailed                             events.EventName = "WorkerSliceGatewayDeletionFailed"
	EventWorkerSliceGatewayDeleted                                    events.EventName = "WorkerSliceGatewayDeleted"
	EventWorkerSliceGatewayCreationFailed                             events.EventName = "WorkerSliceGatewayCreationFailed"
	EventWorkerSliceGatewayCreated                                    events.EventName = "WorkerSliceGatewayCreated"
	EventSliceGatewayJobCreationFailed                                events.EventName = "SliceGatewayJobCreationFailed"
	EventSliceGatewayJobCreated                                       events.EventName = "SliceGatewayJobCreated"
	EventDefaultDeploymentSliceRoleTemplateCreationFailed             events.EventName = "DefaultDeploymentSliceRoleTemplateCreationFailed"
	EventDefaultDeploymentSliceRoleTemplateCreated                    events.EventName = "DefaultDeploymentSliceRoleTemplateCreated"
	EventDefaultReaderSliceRoleTemplateCreationFailed                 events.EventName = "DefaultReaderSliceRoleTemplateCreationFailed"
	EventDefaultReaderSliceRoleTemplateCreated                        events.EventName = "DefaultReaderSliceRoleTemplateCreated"
	EventSliceRoleTemplateDeletionFailed                              events.EventName = "SliceRoleTemplateDeletionFailed"
	EventSliceRoleTemplateDeleted                                     events.EventName = "SliceRoleTemplateDeleted"
	EventSliceResourceQuotaCreationFailed                             events.EventName = "SliceResourceQuotaCreationFailed"
	EventSliceResourceQuotaCreatedOnSliceConfigCreation               events.EventName = "SliceResourceQuotaCreatedOnSliceConfigCreation"
	EventSliceResourceQuotaDeletionFailed                             events.EventName = "SliceResourceQuotaDeletionFailed"
	EventSliceResourceQuotaDeleted                                    events.EventName = "SliceResourceQuotaDeleted"
	EventSliceResourceQuotaRecreationFailed                           events.EventName = "SliceResourceQuotaRecreationFailed"
	EventSliceResourceQuotaRecreated                                  events.EventName = "SliceResourceQuotaRecreated"
	EventSetSliceConfigAsOwnerOfSliceResourceQuotaFailed              events.EventName = "SetSliceConfigAsOwnerOfSliceResourceQuotaFailed"
	EventSetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded           events.EventName = "SetSliceConfigAsOwnerOfSliceResourceQuotaSucceeded"
	EventSliceResourceQuotaCreated                                    events.EventName = "SliceResourceQuotaCreated"
	EventSliceResourceQuotaUpdated                                    events.EventName = "SliceResourceQuotaUpdated"
	EventAllRQSpecificationViolationMetricsResetSuccess               events.EventName = "AllRQSpecificationViolationMetricsResetSuccess"
	EventSliceRQSpecificationViolationMetricsResetSuccess             events.EventName = "SliceRQSpecificationViolationMetricsResetSuccess"
	EventClusterRQSpecificationViolationMetricsResetSuccess           events.EventName = "ClusterRQSpecificationViolationMetricsResetSuccess"
	EventOutdatedNamespaceRQSpecificationViolationMetricsResetSuccess events.EventName = "OutdatedNamespaceRQSpecificationViolationMetricsResetSuccess"
	EventOutdatedClusterRQSpecificationViolationMetricsResetSuccess   events.EventName = "OutdatedClusterRQSpecificationViolationMetricsResetSuccess"
	EventSliceNodeAffinityDeletionFailed                              events.EventName = "SliceNodeAffinityDeletionFailed"
	EventSliceNodeAffinityDeleted                                     events.EventName = "SliceNodeAffinityDeleted"
	EventSetSliceConfigAsOwnerOfSliceNodeAffinityFailed               events.EventName = "SetSliceConfigAsOwnerOfSliceNodeAffinityFailed"
	EventSetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded            events.EventName = "SetSliceConfigAsOwnerOfSliceNodeAffinitySucceeded"
	EventSliceRoleBindingDeletingFailed                               events.EventName = "SliceRoleBindingDeletingFailed"
	EventSliceRoleBindingDeleted                                      events.EventName = "SliceRoleBindingDeleted"
	EventSetSliceConfigAsOwnerOfSliceRoleBindingFailed                events.EventName = "SetSliceConfigAsOwnerOfSliceRoleBindingFailed"
	EventSetSliceConfigAsOwnerOfSliceRoleBindingSucceeded             events.EventName = "SetSliceConfigAsOwnerOfSliceRoleBindingSucceeded"
	EventWorkerSliceRoleBindingReconciliationSuccess                  events.EventName = "WorkerSliceRoleBindingReconciliationSuccess"
	EventWorkerSliceRoleBindingDeletedForcefully                      events.EventName = "WorkerSliceRoleBindingDeletedForcefully"
	EventWorkerSliceRoleBindingRecreationFailed                       events.EventName = "WorkerSliceRoleBindingRecreationFailed"
	EventWorkerSliceRoleBindingRecreated                              events.EventName = "WorkerSliceRoleBindingRecreated"
	EventWorkerSliceRoleBindingCreationFailed                         events.EventName = "WorkerSliceRoleBindingCreationFailed"
	EventWorkerSliceRoleBindingCreated                                events.EventName = "WorkerSliceRoleBindingCreated"
	EventWorkerSliceRoleBindingUpdateFailed                           events.EventName = "WorkerSliceRoleBindingUpdateFailed"
	EventWorkerSliceRoleBindingUpdated                                events.EventName = "WorkerSliceRoleBindingUpdated"
	EventWorkerSliceRoleBindingDeletionFailed                         events.EventName = "WorkerSliceRoleBindingDeletionFailed"
	EventWorkerSliceRoleBindingDeleted                                events.EventName = "WorkerSliceRoleBindingDeleted"
	EventWorkerSliceNodeAffinityDeletedForcefully                     events.EventName = "WorkerSliceNodeAffinityDeletedForcefully"
	EventWorkerSliceNodeAffinityRecreationFailed                      events.EventName = "WorkerSliceNodeAffinityRecreationFailed"
	EventWorkerSliceNodeAffinityRecreated                             events.EventName = "WorkerSliceNodeAffinityRecreated"
	EventNodeAffinityRilesExpansionFailed                             events.EventName = "NodeAffinityRilesExpansionFailed"
	EventSliceNodeAffinityConfigDeepCopyFailed                        events.EventName = "SliceNodeAffinityConfigDeepCopyFailed"
	EventWorkerSliceNodeAffinityCreationFailed                        events.EventName = "WorkerSliceNodeAffinityCreationFailed"
	EventWorkerSliceNodeAffinityCreated                               events.EventName = "WorkerSliceNodeAffinityCreated"
	EventWorkerSliceNodeAffinityUpdateFailed                          events.EventName = "WorkerSliceNodeAffinityUpdateFailed"
	EventWorkerSliceNodeAffinityUpdated                               events.EventName = "WorkerSliceNodeAffinityUpdated"
	EventWorkerSliceNodeAffinityDeletionFailed                        events.EventName = "WorkerSliceNodeAffinityDeletionFailed"
	EventWorkerSliceNodeAffinityDeleted                               events.EventName = "WorkerSliceNodeAffinityDeleted"
	EventWorkerSliceResourceQuotaDeletedForcefully                    events.EventName = "WorkerSliceResourceQuotaDeletedForcefully"
	EventWorkerSliceResourceQuotaRecreationFailed                     events.EventName = "WorkerSliceResourceQuotaRecreationFailed"
	EventWorkerSliceResourceQuotaRecreated                            events.EventName = "WorkerSliceResourceQuotaRecreated"
	EventOffBoardedNamespaceUtilizationMetricsReset                   events.EventName = "OffBoardedNamespaceUtilizationMetricsReset"
	EventResourceQuotaMetricsPopulated                                events.EventName = "ResourceQuotaMetricsPopulated"
	EventClusterCPULimitViolated                                      events.EventName = "ClusterCPULimitViolated"
	EventClusterMemoryLimitViolated                                   events.EventName = "ClusterMemoryLimitViolated"
	EventClusterPodCountViolated                                      events.EventName = "ClusterPodCountViolated"
	EventClusterEphemeralStorageLimitViolated                         events.EventName = "ClusterEphemeralStorageLimitViolated"
	EventClusterCPURequestViolated                                    events.EventName = "ClusterCPURequestViolated"
	EventClusterMemoryRequestViolated                                 events.EventName = "ClusterMemoryRequestViolated"
	EventClusterEphemeralStorageRequestViolated                       events.EventName = "ClusterEphemeralStorageRequestViolated"
	EventNamespaceCPULimitViolated                                    events.EventName = "NamespaceCPULimitViolated"
	EventNamespaceMemoryLimitViolated                                 events.EventName = "NamespaceMemoryLimitViolated"
	EventNamespacePodCountViolated                                    events.EventName = "NamespacePodCountViolated"
	EventNamespaceEphemeralStorageLimitViolated                       events.EventName = "NamespaceEphemeralStorageLimitViolated"
	EventNamespaceCPURequestViolated                                  events.EventName = "NamespaceCPURequestViolated"
	EventNamespaceMemoryRequestViolated                               events.EventName = "NamespaceMemoryRequestViolated"
	EventNamespaceEphemeralStorageRequestViolated                     events.EventName = "NamespaceEphemeralStorageRequestViolated"
	EventSliceCPULimitViolated                                        events.EventName = "SliceCPULimitViolated"
	EventSliceMemoryLimitViolated                                     events.EventName = "SliceMemoryLimitViolated"
	EventSlicePodCountViolated                                        events.EventName = "SlicePodCountViolated"
	EventSliceEphemeralStorageLimitViolated                           events.EventName = "SliceEphemeralStorageLimitViolated"
	EventSliceCPURequestViolated                                      events.EventName = "SliceCPURequestViolated"
	EventSliceMemoryRequestViolated                                   events.EventName = "SliceMemoryRequestViolated"
	EventSliceEphemeralStorageRequestViolated                         events.EventName = "SliceEphemeralStorageRequestViolated"
	EventWorkerSliceResourceQuotaCreationFailed                       events.EventName = "WorkerSliceResourceQuotaCreationFailed"
	EventWorkerSliceResourceQuotaCreated                              events.EventName = "WorkerSliceResourceQuotaCreated"
	EventWorkerSliceResourceQuotaUpdateFailed                         events.EventName = "WorkerSliceResourceQuotaUpdateFailed"
	EventWorkerSliceResourceQuotaUpdated                              events.EventName = "WorkerSliceResourceQuotaUpdated"
	EventWorkerSliceResourceQuotaDeletionFailed                       events.EventName = "WorkerSliceResourceQuotaDeletionFailed"
	EventWorkerSliceResourceQuotaDeleted                              events.EventName = "WorkerSliceResourceQuotaDeleted"
	EventClusterDeboardSuccess                                        events.EventName = "ClusterDeboardSuccess"
)
