name: build-test-kubeslice-controller
on:
  pull_request:
    branches:
    - 'master'
    - 'release-*'
    - 'dev'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          file: unit_tests.dockerfile
          tags: test-image:latest
          push: false
